// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YC3_DAT_VE_CONCERT.Data;

#nullable disable

namespace YC3_DAT_VE_CONCERT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260110095837_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YC3_DAT_VE_CONCERT.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("YC3_DAT_VE_CONCERT.Model.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ticket_price");

                    b.Property<int>("TotalSeat")
                        .HasColumnType("int")
                        .HasColumnName("total_seat");

                    b.Property<int>("VenueId")
                        .HasColumnType("int")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 5, 10, 19, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chuỗi ban nhạc và DJ biểu diễn tại Sân vận động Mỹ Đình.",
                            Name = "Lễ hội Âm nhạc Xuân",
                            TicketPrice = 500000.00m,
                            TotalSeat = 35000,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 6, 12, 19, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Buổi hòa nhạc cổ điển tại Nhà Hát Lớn Hà Nội.",
                            Name = "Đêm Nhạc Cổ Điển",
                            TicketPrice = 350000.00m,
                            TotalSeat = 1000,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2026, 7, 5, 20, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Các ban nhạc indie và nghệ sĩ trẻ biểu diễn ở Nhà Văn Hóa Thanh Niên.",
                            Name = "Indie Showcase TP.HCM",
                            TicketPrice = 200000.00m,
                            TotalSeat = 800,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2026, 8, 20, 20, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Đêm nhạc jazz lãng mạn tại Hà Nội.",
                            Name = "Đêm Jazz Mùa Hè",
                            TicketPrice = 300000.00m,
                            TotalSeat = 900,
                            VenueId = 1
                        });
                });

            modelBuilder.Entity("YC3_DAT_VE_CONCERT.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("order_date");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("YC3_DAT_VE_CONCERT.Model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("YC3_DAT_VE_CONCERT.Model.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("purchase_date");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("seat_number");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EventId");

                    b.HasIndex("OrderId");

                    b.ToTable("tickets");
                });

            modelBuilder.Entity("YC3_DAT_VE_CONCERT.Model.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 1200,
                            Location = "1 Tràng Tiền, Hoàn Kiếm, Hà Nội",
                            Name = "Nhà Hát Lớn Hà Nội"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 40000,
                            Location = "Mỹ Đình, Nam Từ Liêm, Hà Nội",
                            Name = "Sân vận động Mỹ Đình"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 2000,
                            Location = "4 Phạm Ngọc Thạch, Quận 1, TP. Hồ Chí Minh",
                            Name = "Nhà Văn Hóa Thanh Niên"
                        });
                });

            modelBuilder.Entity("YC3_DAT_VE_CONCERT.Model.Customer", b =>
                {
                    b.HasOne("YC3_DAT_VE_CONCERT.Model.Role", "Role")
                        .WithMany("Customers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("YC3_DAT_VE_CONCERT.Model.Event", b =>
                {
                    b.HasOne("YC3_DAT_VE_CONCERT.Model.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("YC3_DAT_VE_CONCERT.Model.Order", b =>
                {
                    b.HasOne("YC3_DAT_VE_CONCERT.Model.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("YC3_DAT_VE_CONCERT.Model.Ticket", b =>
                {
                    b.HasOne("YC3_DAT_VE_CONCERT.Model.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("YC3_DAT_VE_CONCERT.Model.Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YC3_DAT_VE_CONCERT.Model.Order", "Order")
                        .WithMany("Tickets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Event");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("YC3_DAT_VE_CONCERT.Model.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("YC3_DAT_VE_CONCERT.Model.Event", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("YC3_DAT_VE_CONCERT.Model.Order", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("YC3_DAT_VE_CONCERT.Model.Role", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("YC3_DAT_VE_CONCERT.Model.Venue", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
